using System;
using System.Drawing;

using Grasshopper.Kernel;

using Rhino;
using Rhino.Display;
using Rhino.Geometry;

using Tunny.Component.Params;

namespace Tunny.Component.Util
{
    public class FishPrintByCapture : GH_Component
    {
        public FishPrintByCapture()
          : base("Fish Print by Capture", "FPCap",
              "Creates a capture of the currently active viewport.",
              "Tunny", "Util")
        {
        }

        public override BoundingBox ClippingBox => new BoundingBox(new Point3d(-1e+10, -1e+10, -1e+10), new Point3d(1e+10, 1e+10, 1e+1));
        public override bool IsPreviewCapable => true;

        protected override void RegisterInputParams(GH_InputParamManager pManager)
        {
            pManager.AddGeometryParameter("Geometry", "Geom", "Please enter the geometry being generated by the GH you wish to capture. Failure to do so may result in an inaccurate capture.", GH_ParamAccess.list);
        }

        protected override void RegisterOutputParams(GH_OutputParamManager pManager)
        {
            pManager.AddParameter(new Param_FishPrint(), "FishPrint", "FPrint", "FishPrint", GH_ParamAccess.item);
        }

        private readonly RhinoDoc _doc = RhinoDoc.ActiveDoc;
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            RhinoView activeView = _doc.Views.ActiveView;
            Bitmap bitmap = activeView.CaptureToBitmap();

            DA.SetData(0, bitmap);
        }

        protected override Bitmap Icon => null;
        public override Guid ComponentGuid => new Guid("5CFA19E3-2FBE-45D3-8E40-EF459C7FF491");
    }
}
